# configs/08_cartpole.yaml
parent_pool_size: 10
offspring_pool_size: 20
max_generations: 10
num_elites: 2

evolution:
  strategy: mu_plus_lambda

modules:
  brain:
    type: evonet
    dim: [4, 8, 2]     # 4 obs, 2 actions
    activation: [tanh, tanh, linear]
    recurrent: none
    initializer: identity_evonet

    weights:
      bounds: [-2.0, 2.0]

    bias:
      bounds: [-1.0, 1.0]

    mutation:
      strategy: adaptive_individual
      min_strength: 0.01
      max_strength: 0.1
      probability: 0.6
