# Sample configuration for 01_netvector_sine_approximation.py

parent_pool_size: 20
offspring_pool_size: 140
max_generations: 150
max_indiv_age: 0
num_elites: 2

evolution:
  strategy: mu_comma_lambda

modules:
  nnet:
    type: vector
    structure: net
    dim: [1, 16, 16, 1]
    initializer: normal
    activation: tanh
    bounds: [-1.0, 1.0]
    mutation:
      strategy: exponential_decay
      init_strength: 0.05
      min_strength: 0.01
      max_strength: 0.1
      min_probability: 1.0
      max_probability: 1.0
