# Sample configuration for 02_sine_delay.yaml

random_seed: 1  # Global random seed for reproducibility.

parent_pool_size: 20
offspring_pool_size: 60
max_generations: 50
max_indiv_age: 0
num_elites: 2

evolution:
  strategy: mu_comma_lambda

modules:
  nnet:
    type: evonet
    dim: [1, 1, 1]
    activation: ["linear", "linear", "linear"]
    initializer: normal_evonet
    
    weights:
      initializer: normal
      bounds: [-1.0, 1.0]

    recurrent: direct

    delay:
      initializer: fixed
      value: 15

    mutation:
      strategy: constant
      strength: 0.05
      probability: 1.0
