# Sample configuration for 03_delay_bitseq_echo.py

random_seed: 1

parent_pool_size: 20
offspring_pool_size: 60
max_generations: 100
max_indiv_age: 0
num_elites: 2

evolution:
  strategy: mu_comma_lambda

modules:
  nnet:
    type: evonet
    dim: [1, 3, 1]
    activation: ["linear", "tanh", "sigmoid"]
    initializer: normal_evonet

    weights:
      initializer: normal
      std: 0.5
      bounds: [-2.0, 2.0]

    bias:
      initializer: zero
        #      std: 0.2
        #bounds: [-0.0, 0.0]

    recurrent: direct

    delay:
      initializer: uniform
      bounds: [1, 10]

    mutation:
      strategy: constant

      strength: 0.05
      probability: 1.0

      delay:
        probability: 0.1
        mode: delta_step
        delta: 1
        bounds: [1, 10]
      
      biases:
        strategy: constant
        probability: 0.0
        strength: 0.0
