# Sample configuration for 04_temporal_smoothing_leaky.yaml

parent_pool_size: 30
offspring_pool_size: 61
max_generations: 80
num_elites: 2
random_seed: 1

evolution:
  strategy: mu_plus_lambda

modules:
  nnet:
    type: evonet
    dim: [1, 6, 1]
    activation: [linear, tanh, sigmoid]

    weights:
      initializer: uniform
      bounds: [-2.0, 2.0]

    bias:
      initializer: uniform
      bounds: [-1.0, 1.0]

    # Hidden layer is leaky
    neuron_dynamics:
      - name: standard
        params: {}
      - name: leaky
        params:
          alpha: 0.15
      - name: standard
        params: {}

    mutation:
      strategy: constant
      strength: 0.20
      probability: 0.80

