# Sample configuration for 06_structural_xor.py

parent_pool_size: 20
offspring_pool_size: 40
max_generations: 200
max_indiv_age: 0
num_elites: 0

stopping:
  target_fitness: 0.001

evolution:
  strategy: mu_plus_lambda

modules:
  brain:
    type: evonet
    dim: [2, 0, 0, 1]
    activation: [linear, tanh, tanh, sigmoid]
    initializer: unconnected_evonet

    weights:
      bounds: [-5.0, 5.0]

    bias:
      bounds: [-1.0, 1.0]

    mutation:
      strategy: constant
      strength: 0.1
      probability: 0.9

      biases:
        strategy: constant
        strength: 0.05
        probability: 0.8

      structural:
        add_neuron: 
          probability: 0.03
          init_connection_ratio: 1.0
          activations_allowed: [tanh]
          init: random

        remove_neuron:
          probability: 0.01

        add_connection: 
          probability: 0.05

        remove_connection:
          probability: 0.01

        topology:
          connection_scope: crosslayer
          recurrent: "none"  # Optionen: none | direct | local | all
          max_neurons: 3
          max_connections: 20
