# Sample configuration for 07_recurrent_bit_prediction

random_seed: 42

parent_pool_size: 20
offspring_pool_size: 60
max_generations: 500
max_indiv_age: 0
num_elites: 2

evolution:
  strategy: mu_plus_lambda

modules:
  brain:
    type: evonet
    dim: [1, 8, 1]
    activation: [linear, tanh, sigmoid]
    recurrent: "local"

    weights:
      initializer: zero
      bounds: [-5.0, 5.0]

    bias:
      initializer: zero
      bounds: [-1.0, 1.0]

    mutation:
      strategy: adaptive_individual
      min_strength: 0.005
      max_strength: 0.2
      probability: 0.5
