# Sample configuration for 08_recurrent_timeseries.py
#random_seed: 42

parent_pool_size: 80
offspring_pool_size: 400
max_generations: 100
num_elites: 8

evolution:
  strategy: mu_plus_lambda

modules:
  brain:
    type: evonet
    dim: [1, 8, 1]
    activation: [linear, tanh, tanh]
    recurrent: "all"
    initializer: identity_evonet

    weights:
      bounds: [-5.0, 5.0]

    bias:
      bounds: [-1.0, 1.0]

    mutation:
      strategy: adaptive_individual
      min_strength: 0.002
      max_strength: 0.1
      probability: 0.6
