name: Code Quality and Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"


      - name: Install project and tools
        run: |
          pip install -r requirements-dev.txt
          pip install -e . --no-deps
          
          # Linter, Formatter, Typechecker, Testing Tools
          pip install \
            black==25.1.0 \
            isort \
            flake8 \
            mypy==1.16.1 \
            pytest \
            docformatter \
            types-PyYAML \
            matplotlib \
            gymnasium \
            imageio

      - name: Run black
        run: black --check evolib/ tests/

      - name: Run isort
        run: |
          echo "::group::Check import order with isort"
          isort evolib tests --check-only --diff
          echo "::endgroup::"

      - name: Run flake8
        run: flake8 evolib/ tests/

      - name: Install package + test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Run mypy
        run: mypy evolib/

      - name: Run pytest
        run: pytest tests/

      - name: Run docformatter
        run: docformatter --check --recursive evolib tests
